source=/home/zei/.config/mango/config/env.conf
source=/home/zei/.config/mango/config/programs.conf
source=/home/zei/.config/mango/config/appearance.conf
source=/home/zei/.config/mango/config/animations.conf
source=/home/zei/.config/mango/config/layouts.conf
source=/home/zei/.config/mango/config/input.conf
source=/home/zei/.config/mango/config/binds.conf
source=/home/zei/.config/mango/config/autostart.conf
