tag_num=10
circle_layout=tile,scroller,center_tile,grid,deck,monocle,vertical_scroller
new_is_master=1
default_mfact=0.55
default_nmaster=1

tagrule=id:1,layout_name:tile,no_hide:1
tagrule=id:2,layout_name:scroller,no_hide:1
tagrule=id:3,layout_name:center_tile,no_hide:1
tagrule=id:4,layout_name:grid,no_hide:1
tagrule=id:5,layout_name:deck,no_hide:1
tagrule=id:6,layout_name:monocle
tagrule=id:7,layout_name:vertical_scroller
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile
tagrule=id:10,layout_name:tile

scroller_structs=20
scroller_default_proportion=0.8
scroller_default_proportion_single=1.0
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_proportion_preset=0.5,0.8,1.0

enable_hotarea=0
hotarea_disable_on_fullscreen=1
overviewgappi=6
overviewgappo=12
overcircle_center_ratio=0.5

scratchpad_width_ratio=0.75
scratchpad_height_ratio=0.75
windowrule=isnamedscratchpad:1,appid:^archnemesis-scratch$
