bind=SUPER,Return,spawn,kitty
bind=SUPER,b,spawn,helium-browser
bind=SUPER,e,spawn,dolphin
bind=SUPER,space,spawn,sh -c '"$HOME/.config/rofi/launchers/launcher.sh"'
bind=SUPER,g,spawn,kdenlive
bind=SUPER,n,spawn,kitty nvim
bind=SUPER,v,spawn,sh -c '"$HOME/.config/rofi/clipboard/clipboard.sh"'
