# ╭────────────────────────────────────────────╮
# │             A R C H N E M E S I S          │
# │                  HYPRLOCK                  │
# ╰────────────────────────────────────────────╯

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = __WALLPAPER__
    color = rgba(25, 23, 36, 1.0)

    blur_passes = 2
    blur_size = 7

    brightness = 0.65
    contrast = 1.05
    vibrancy = 0.15
    vibrancy_darkness = 0.0
}

# Clock
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"

    color = rgba(224, 222, 244, 1.0)
    font_size = 78
    font_family = Iosevka Nerd Font Mono

    position = 0, 120
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"

    color = rgba(196, 167, 231, 1.0)
    font_size = 16
    font_family = Iosevka Nerd Font Mono

    position = 0, 45
    halign = center
    valign = center
}

# ARCHNEMESIS
label {
    monitor =
    text = A R C H N E M E S I S

    color = rgba(156, 207, 216, 1.0)
    font_size = 13
    font_family = Iosevka Nerd Font Mono

    position = 0, -40
    halign = center
    valign = center
}

# Password
input-field {
    monitor =

    size = 300, 52
    position = 0, -125

    dots_size = 0.22
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgba(196, 167, 231, 0.70)
    inner_color = rgba(25, 23, 36, 0.55)
    font_color = rgba(224, 222, 244, 1.0)

    fade_on_empty = false
    placeholder_text =   Password

    rounding = 12
    shadow_passes = 1

    halign = center
    valign = center
}

# User
label {
    monitor =
    text = $USER

    color = rgba(144, 140, 170, 1.0)
    font_size = 12
    font_family = Iosevka Nerd Font Mono

    position = 0, -180
    halign = center
    valign = center
}
